version: '3.8'

services:
  # PostgreSQL Database (same for dev)
  postgres:
    image: postgres:15-alpine
    container_name: rsud-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: rsud_anugerah_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rsud-dev-network

  # Backend API (Development with hot reload)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: rsud-backend-dev
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/rsud_anugerah_dev
      JWT_SECRET: dev-jwt-secret-key
      NODE_ENV: development
      PORT: 3001
    ports:
      - "3001:3001"
      - "9229:9229"  # Debug port
    depends_on:
      - postgres
    networks:
      - rsud-dev-network
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist
    command: npm run start:dev

  # Frontend (Development with hot reload)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: rsud-frontend-dev
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - rsud-dev-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

volumes:
  postgres_dev_data:
    driver: local

networks:
  rsud-dev-network:
    driver: bridge
